export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';

export const ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED';
export const ITEMS_IS_LOADING = 'ITEMS_IS_LOADING';

export const ITEMS_FETCH_RESULT_SUCCESS = 'ITEMS_FETCH_RESULT_SUCCESS';
export const ITEMS_FETCH_LIGNE_SUCCESS = 'ITEMS_FETCH_LIGNE_SUCCESS';
export const ITEMS_FETCH_COMPOSANTS_SUCCESS = 'ITEMS_FETCH_COMPOSANTS_SUCCESS';
export const ITEMS_FETCH_COMPOSANTS_R_SUCCESS = 'ITEMS_FETCH_COMPOSANTS_R_SUCCESS';
export const ITEMS_FETCH_VOISINS_R_SUCCESS = 'ITEMS_FETCH_VOISINS_R_SUCCESS';
export const ITEMS_FETCH_COMPOSANTS_A_SUCCESS = 'ITEMS_FETCH_COMPOSANTS_A_SUCCESS';
export const ITEMS_FETCH_VOISINS_A_SUCCESS = 'ITEMS_FETCH_VOISINS_A_SUCCESS';
export const DATA_POST_SCENARIO_SUCCESS = 'DATA_POST_SCENARIO_SUCCESS';

export const ADD_SCENARIO_AUGMENTATION_LIEN = 'ADD_SCENARIO_AUGMENTATION_LIEN';
export const ADD_SCENARIO_AUGMENTATION_LIGNE = 'ADD_SCENARIO_AUGMENTATION_LIGNE';
export const ADD_SCENARIO_AUGMENTATION_NOEUD = 'ADD_SCENARIO_AUGMENTATION_NOEUD';

export const ADD_SCENARIO_REDUCTION_LIEN = 'ADD_SCENARIO_REDUCTION_LIEN';
export const ADD_SCENARIO_REDUCTION_LIGNE = 'ADD_SCENARIO_REDUCTION_LIGNE';
export const ADD_SCENARIO_REDUCTION_TRAIN = 'ADD_SCENARIO_REDUCTION_TRAIN';

export const ADD_SCENARIO_PERTURBATION = 'ADD_SCENARIO_PERTURBATION';

export const TOGGLE_SCENARIO = 'TOGGLE_SCENARIO';
export const DELETE_SCENARIO = 'DELETE_SCENARIO';
export const DELETE_COMPOSANT = 'DELETE_COMPOSANT';
export const DELETE_VOISIN = 'DELETE_VOISIN';


